import React, { useEffect, useMemo, useState } from 'react';
import { Users, Calendar, Clock, FileText, Plane, Trophy, CheckCircle2, RefreshCw, MapPin } from 'lucide-react';
import { sendClaimRequest } from './archive-claims.js';

const monthLabel = value => value ? new Date(value + '-15T12:00:00Z').toLocaleDateString('id-ID', { month: 'long', year: 'numeric', timeZone: 'UTC' }) : 'Bulanan';
const ratio = (a, b) => b ? `${(100 * a / b).toLocaleString('id-ID', { maximumFractionDigits: 1 })}%` : '—';
const clock = value => value == null ? '—' : `${String(Math.floor(value / 60)).padStart(2, '0')}:${String(Math.round(value % 60)).padStart(2, '0')}`;
const total = (rows, key) => rows.reduce((sum, row) => sum + (Number(row[key]) || 0), 0);
const occurrences = rows => rows.reduce((sum, row) => sum + (row.count ?? 1), 0);
function Metric({ icon: Icon, label, value, detail }) {
  return <div className="rounded-2xl border border-slate-200 bg-white p-5 flex justify-between gap-3"><div><p className="uppercase tracking-wide text-[10px] font-bold text-slate-500">{label}</p><strong className="block text-2xl mt-2 text-slate-900">{value}</strong><p className="text-xs text-slate-500 mt-1">{detail}</p></div><Icon className="rounded-full bg-cyan-100 text-[#1C465F] p-3 shrink-0" size={48}/></div>;
}
function LeaderList({ title, rows, metric, suffix = 'kali' }) {
  return <div className="rounded-2xl border bg-white overflow-hidden"><h3 className="bg-[#1C465F] text-white px-4 py-3 text-xs font-bold uppercase">{title}</h3><div className="p-4 space-y-4">{rows.length ? rows.map(row => <div key={row.nip} className="flex justify-between gap-4 text-xs border-b border-slate-100 pb-3"><span>{row.nama}<small className="block text-slate-500 mt-1">{row.unit}</small></span><strong className="shrink-0">{row[metric]} {suffix}</strong></div>) : <p className="text-xs text-slate-500">Tidak ada catatan.</p>}</div></div>;
}
export function MonthlyRecap({ endpoint, publicView = false }) {
  const [module, setModule] = useState('uang-makan');
  const [month, setMonth] = useState('');
  const [unit, setUnit] = useState('');
  const [data, setData] = useState(null), [error, setError] = useState(''), [loading, setLoading] = useState(true), [reload, setReload] = useState(0);
  useEffect(() => {
    let cancelled = false;
    setLoading(true); setError(''); setData(null);
    sendClaimRequest(endpoint, { action: publicView ? 'rekap_bulanan_publik' : 'rekap_bulanan', modul: module, month }).then(result => {
      if (!Array.isArray(result.employees) || !Array.isArray(result.months)) throw Error('Deploy backend terbaru untuk mengaktifkan Rekap Bulanan.');
      if (publicView && result.publicView !== true) throw Error('Deploy backend terbaru untuk mengaktifkan rekap publik.');
      if (!cancelled) setData(result);
    }).catch(err => { if (!cancelled) setError(err.message); }).finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
  }, [endpoint, module, month, reload, publicView]);
  const units = [...new Set((data?.employees || []).map(row => row.unit))].sort();
  const chosenUnit = units.includes(unit) ? unit : '';
  const rows = useMemo(() => (data?.employees || []).filter(row => !chosenUnit || row.unit === chosenUnit), [data, chosenUnit]);
  const inScope = row => publicView ? !chosenUnit || row.unit === chosenUnit : rows.some(person => person.nip === row.nip);
  const daily = (data?.daily || []).filter(inScope);
  const documents = (data?.documents || []).filter(inScope);
  const trips = documents.filter(row => row.type === 'spt');
  const days = [...new Set(daily.filter(row => !row.libur).map(row => row.tanggal))];
  const dailyWfo = days.map(date => ({ date, count: occurrences(daily.filter(row => row.tanggal === date && row.status === 'WFO' && row.hadir)) })).sort((a,b) => b.count - a.count || a.date.localeCompare(b.date));
  const arrivals = daily.filter(row => row.hadir && row.arrival !== null).map(row => row.arrival);
  const eligible = rows.filter(row => row.assessed >= 5);
  const discipline = [...eligible].sort((a,b) => b.clean / b.assessed - a.clean / a.assessed || b.assessed - a.assessed || a.nama.localeCompare(b.nama)).slice(0,5);
  const punctual = [...eligible].sort((a,b) => b.onTime / b.assessed - a.onTime / a.assessed || b.assessed - a.assessed || (a.avgArrival ?? 1440) - (b.avgArrival ?? 1440)).slice(0,5);
  const top = key => rows.filter(row => row[key] > 0).sort((a,b) => b[key] - a[key] || a.nama.localeCompare(b.nama)).slice(0,5);
  const destinations = Object.entries(trips.reduce((counts, trip) => { counts[trip.tujuan || 'Tujuan belum tersedia'] = (counts[trip.tujuan || 'Tujuan belum tersedia'] || 0) + (trip.count ?? 1); return counts; }, {})).sort((a,b) => b[1]-a[1]);
  return <div className="space-y-8 max-w-7xl mx-auto" aria-label="Rekap Bulanan">
    <div className="sticky top-0 z-20 bg-[#F8FAFC] py-3 space-y-3 border-b">
      <div className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-xl font-extrabold text-[#1C465F]">Rekap Bulanan</h1><div className="flex flex-wrap gap-2 text-xs">
        <select aria-label="Sumber modul rekap" value={module} onChange={e => { setModule(e.target.value); setMonth(''); }} className="border rounded-xl p-2 bg-white"><option value="uang-makan">Uang Makan</option><option value="tukin">Tunjangan Kinerja</option></select>
        <select aria-label="Bulan rekap" value={data?.month || month} disabled={loading || !data?.months.length} onChange={e => setMonth(e.target.value)} className="border rounded-xl p-2 bg-white">{!data?.months.length && <option value="">Belum ada data</option>}{data?.months.map(value => <option key={value} value={value}>{monthLabel(value)}</option>)}</select>
        <select aria-label="Filter SubUnit Kerja" value={chosenUnit} onChange={e => setUnit(e.target.value)} className="border rounded-xl p-2 bg-white max-w-xs"><option value="">Semua SubUnit Kerja</option>{units.map(value => <option key={value}>{value}</option>)}</select>
        <button aria-label="Muat ulang rekap" disabled={loading} onClick={() => setReload(v=>v+1)} className="p-2 border rounded-xl bg-white"><RefreshCw size={16} className={loading ? 'animate-spin' : ''}/></button>
      </div></div>
      <nav className="flex gap-4 overflow-auto text-xs font-bold text-[#1C465F]">{[['ringkasan','Ringkasan'],['kehadiran','Kehadiran'],['unit','Per Unit'],['juara','Juara'],['catatan','Catatan'],['dinas','Dinas']].map(([id,label])=><a key={id} href={'#rekap-'+id} onClick={event=>{ event.preventDefault(); document.getElementById('rekap-'+id)?.scrollIntoView({behavior:'smooth',block:'start'}); }} className="py-2 shrink-0">{label}</a>)}</nav>
    </div>
    {loading && <p role="status" className="p-6 text-slate-500">Memuat rekap bulanan...</p>}
    {error && <p role="alert" className="bg-red-50 text-red-700 rounded-xl p-4">{error}</p>}
    {data && <>
      <section id="rekap-ringkasan" className="scroll-mt-32 rounded-3xl bg-gradient-to-br from-[#1C465F] to-[#0A2235] text-white p-6 md:p-10 space-y-6"><span className="text-xs uppercase font-bold rounded-full bg-[#D5C58A] text-[#1C465F] px-3 py-1">{monthLabel(data.month)}</span><h2 className="text-3xl md:text-4xl font-black">Rekap {monthLabel(data.month)}<br/><span className="text-[#D5C58A]">{rows.length ? 'sudah tersedia' : 'belum tersedia'}</span></h2><p className="text-sm text-slate-200">Hasil konfirmasi tab 4, berdasarkan tanggal kalender pada {module === 'tukin' ? 'Tunjangan Kinerja' : 'Uang Makan'}. {chosenUnit || 'Seluruh SubUnit Kerja'}.</p><div className="grid sm:grid-cols-3 gap-4">{[[Users,rows.length,'Pegawai dengan rekap'],[Calendar,days.length,'Tanggal kerja tercatat'],[Clock,ratio(total(rows,'masuk'),total(rows,'hariKerja')),'Tingkat masuk WFO/WFA/WFH']].map(([Icon,value,label])=><div key={label} className="border border-white/20 bg-white/10 rounded-2xl p-5"><Icon size={24}/><strong className="block text-3xl mt-3">{value}</strong><span className="text-xs text-slate-200">{label}</span></div>)}</div><p className="text-xs text-slate-300">Tidak menggabungkan kedua modul agar pegawai/tanggal tidak terhitung dua kali. Rekap yang menunggu hitung ulang tidak dimasukkan.</p></section>
      {!rows.length ? <div className="bg-white rounded-2xl border p-8 text-center text-sm text-slate-500">Belum ada hasil perhitungan untuk pilihan ini. Konfirmasikan tab 4 pada submisi pegawai terlebih dahulu. Data lama sebelum fitur ini memerlukan perhitungan ulang satu kali.</div> : <>
        <section id="rekap-kehadiran" className="scroll-mt-32 space-y-5"><h2 className="text-xl font-bold text-center">Statistik Kehadiran</h2><div className="grid md:grid-cols-3 gap-4"><Metric icon={Clock} label="Presensi paling awal" value={arrivals.length?clock(Math.min(...arrivals)):'—'} detail="Jam datang WFO/WFA/WFH"/><Metric icon={CheckCircle2} label="Total masuk kerja" value={total(rows,'masuk')} detail="Hari-orang WFO/WFA/WFH"/><Metric icon={FileText} label="Dokumen pendukung" value={occurrences(documents)} detail="Bukti aktif pada tanggal bulan ini"/><Metric icon={Calendar} label="Cuti" value={total(rows,'cuti')} detail="Hari-orang cuti"/><Metric icon={Plane} label="Perjalanan dinas" value={occurrences(trips)} detail="Pasangan pegawai dan surat tugas"/><Metric icon={Clock} label="Total hari dinas" value={total(rows,'dinas')} detail="Akumulasi hari-orang"/></div><div className="grid md:grid-cols-2 gap-4">{[['Hari teramai',dailyWfo[0]],['Hari tersepi',dailyWfo[dailyWfo.length-1]]].map(([title,item])=><div key={title} className="rounded-2xl p-5 bg-[#1C465F] text-white"><h3 className="text-xs uppercase text-[#D5C58A] font-bold">{title}</h3><strong className="block mt-2">{item?.date || '—'}</strong><p className="text-xs mt-1">{item?.count || 0} pegawai hadir WFO</p></div>)}</div></section>
        <section id="rekap-unit" className="scroll-mt-32 space-y-5"><h2 className="text-xl font-bold text-center">Sebaran per SubUnit Kerja</h2><p className="text-xs text-center text-slate-500">Klik kartu untuk menyaring seluruh halaman.</p><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{units.filter(value=>!chosenUnit||value===chosenUnit).map(value=>{const group=(data.employees||[]).filter(row=>row.unit===value);return <button key={value} onClick={()=>setUnit(chosenUnit===value?'':value)} className="rounded-2xl border bg-white text-left overflow-hidden"><div className="bg-[#1C465F] text-white p-4 text-xs font-bold">{value}<span className="block mt-2 font-normal">{group.length} pegawai</span></div><div className="grid grid-cols-2 gap-4 p-4 text-xs">{[['Tingkat masuk',ratio(total(group,'masuk'),total(group,'hariKerja'))],['Hari masuk',total(group,'masuk')],['Hari dinas',total(group,'dinas')],['Hari cuti',total(group,'cuti')]].map(([label,val])=><div key={label}><span className="text-slate-500">{label}</span><strong className="block text-xl mt-1">{val}</strong></div>)}</div></button>;})}</div></section>
        <section id="rekap-juara" className="scroll-mt-32 space-y-5"><h2 className="text-xl font-bold text-center flex items-center justify-center gap-2"><Trophy size={22}/>Apresiasi Kedisiplinan</h2><p className="text-xs text-slate-500">Minimal 5 hari WFO dinilai. Persentase hari tanpa TL, PSW, dan lupa absen; nilai sama diurutkan menurut jumlah hari yang dinilai. Dinas/Cuti/TB/Libur tidak dinilai.</p><div className="grid sm:grid-cols-2 xl:grid-cols-5 gap-4">{discipline.map((row,i)=><article key={row.nip} className="rounded-2xl overflow-hidden border bg-[#1C465F] text-white"><div className="h-32 bg-cyan-100 flex items-center justify-center relative">{row.photo ? <img src={row.photo} alt="" className="w-full h-full object-cover" onError={e=>{e.currentTarget.hidden=true;}}/>:<Users size={40} className="text-cyan-600"/>}<span className="absolute left-2 top-2 text-xs bg-white text-[#1C465F] rounded-full px-2 py-1">#{i+1}</span></div><div className="p-4"><h3 className="text-xs font-bold">{row.nama}</h3><p className="text-xs mt-2">{ratio(row.clean,row.assessed)} · {row.clean}/{row.assessed} hari WFO</p><p className="text-[10px] mt-1 text-cyan-100">{row.unit}</p></div></article>)}</div>{!discipline.length&&<p className="text-sm text-slate-500">Belum ada pegawai dengan minimal 5 hari WFO yang dapat dinilai.</p>}<div className="border rounded-2xl bg-white p-5 space-y-3"><h3 className="font-bold">Paling Tepat Waktu</h3><p className="text-xs text-slate-500">Kedatangan tidak melewati jam masuk jadwal (tanpa flexi), berdasarkan hari WFO.</p>{punctual.map((row,i)=><div key={row.nip} className="border-b pb-3 text-xs flex flex-wrap justify-between gap-3"><span>#{i+1} {row.nama} · {row.unit}</span><strong>{ratio(row.onTime,row.assessed)} · rata-rata {clock(row.avgArrival)}</strong></div>)}</div></section>
        <section id="rekap-catatan" className="scroll-mt-32 space-y-5"><h2 className="text-xl font-bold text-center">Catatan untuk Perbaikan</h2><div className="grid md:grid-cols-3 gap-4"><LeaderList title="Terlambat" rows={top('terlambat')} metric="terlambat" suffix="hari"/><LeaderList title="Pulang sebelum waktunya" rows={top('psw')} metric="psw" suffix="hari"/><LeaderList title="Lupa absen" rows={top('lupaAbsen')} metric="lupaAbsen"/></div><div className="overflow-auto bg-white rounded-2xl border"><table className="w-full min-w-[650px] text-xs"><thead><tr>{['Pegawai','SubUnit','Lupa Absen','Adjustment','Tidak Absen'].map(label=><th key={label} className="p-3 text-left bg-slate-100">{label}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.nip} className="border-t"><td className="p-3">{row.nama}</td><td className="p-3">{row.unit}</td><td className="p-3">{row.lupaAbsen}</td><td className="p-3">{row.adjusted}</td><td className="p-3">{row.unadjusted}</td></tr>)}</tbody></table></div></section>
        <section id="rekap-dinas" className="scroll-mt-32 rounded-2xl bg-white border p-6 space-y-5 text-center"><h2 className="text-xl font-bold flex justify-center gap-2 items-center"><MapPin size={22}/>Tujuan Perjalanan Dinas</h2><div className="flex flex-wrap justify-center gap-3">{destinations.map(([name,count])=><span key={name} className="border rounded-full px-4 py-2 text-xs">{name} <strong className="ml-2 text-[#1C465F]">{count}×</strong></span>)}</div><p className="bg-[#1C465F] rounded-2xl p-6 text-white"><strong className="block text-4xl">{occurrences(trips)}</strong><span className="text-sm">Perjalanan dinas pegawai</span></p></section>
      </>}
    </>}
  </div>;
}
